name: Compile Rainbow Six Siege Asian Server filter geoip source file

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  geoip-r6s-compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Necessary Tools
      run: |
        sudo apt install -y jq wget curl

    - name: Install sing-box
      run: |
        sudo curl -fsSL https://sing-box.app/gpg.key -o /etc/apt/keyrings/sagernet.asc
        sudo chmod a+r /etc/apt/keyrings/sagernet.asc
        echo "deb [arch=`dpkg --print-architecture` signed-by=/etc/apt/keyrings/sagernet.asc] https://deb.sagernet.org/ * *" | \
        sudo tee /etc/apt/sources.list.d/sagernet.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y sing-box
    
    - name: Pull code from remote
      run: gh repo clone HXHGTS/AzureIPGet
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Format Source
      run: |
        jq '.route | {version: 1, rules: [.rules[] | del(.outbound)]}' ./AzureIPGet/data/AzureIPBlock.json > AzureIPBlockRule.json
        sing-box rule-set compile --output geoip-r6hkonly.srs AzureIPBlockRule.json
        rm -rf ./AzureIPGet AzureIPBlockRule.json

    - name: Push Files
      run: |
        sudo mkdir -p NewRelease/geoip
        sudo mv -f geoip-r6hkonly.srs NewRelease/geoip/geoip-r6hkonly.srs
        sudo chown -R $USER:$USER NewRelease
        sudo chmod -R 777 NewRelease
        git config --global user.email "${{ secrets.GH_EMAIL }}"
        git config --global user.name "github-actions[bot]"
        sudo git add NewRelease/geoip/*.srs
        git fetch
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m "Auto Compile telegram geoip source file"
          git push --force origin main:geoip
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ACTIONS_RUNNER_DEBUG: true
        ACTIONS_STEP_DEBUG: true

    - name: Create tag
      id: create_tag
      run: |
        TAG_NAME=$(date -u +"%Y%m%d%H%M%S")
        if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
          echo "Tag $TAG_NAME already exists, deleting it from remote."
          git push --delete origin "$TAG_NAME"
          while git ls-remote --tags origin | grep -q "refs/tags/$TAG_NAME"; do
            echo "Waiting for tag $TAG_NAME to be deleted..."
            sleep 5
          done
        fi
        git tag $TAG_NAME
        git push --force origin $TAG_NAME
        echo "::set-output name=TAG_NAME::$TAG_NAME"

    - name: Create release
      id: create_release
      run: |
        TAG_NAME=${{ steps.create_tag.outputs.TAG_NAME }}
        RELEASE_ID=$(gh release view "$TAG_NAME" --json id --jq '.id' || echo "null")
        if [ "$RELEASE_ID" != "null" then
          echo "Release $TAG_NAME already exists, deleting it."
          gh release delete "$TAG_NAME" --yes
        fi
        gh release create "$TAG_NAME" --title "$TAG_NAME" --notes "Auto-generated release for $TAG_NAME" NewRelease/geoip/geoip-r6hkonly.srs
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
